svn merge RB-8.1.2 trunk

diff --git a/util/repl_check_sync b/util/repl_check_sync
--- a/util/repl_check_sync
+++ b/util/repl_check_sync
@@ -131,6 +131,13 @@ fi
 ###############################################################################
 # STEP 2 : repl_agent status prints
 ###############################################################################
+which telnet 2> /dev/null > /dev/null
+if [ $? -ne 0 ]
+then
+  echo "telnet: command not found"
+  exit 1
+fi
+
 echo "    IP   MasterID SlaveID ForRecovery Status FinalLSA ReplCnt CurRepl SafePageID"
 echo "" > .tmp.out
 echo "" > .result.out
